### ISSUE TITLE
Cloud Logging: High Memory Usage with Logging Logback

### ISSUE THREAD

**Issue by deepfriedbrain** [googleapis/java-logging-logback#136]
#### Environment details

GAE Java 11 Runtime

I've added the following dependency:
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-logging-logback</artifactId>
    <version>0.118.0-alpha</version>
</dependency>
```

#### Steps to reproduce

I'm preparing to migrate my GAE Java 8 runtime app to Java 11 runtime. I deployed a single servlet test app to Java 11 runtime and included the above mentioned dependency for Logging Logback. 

I had 2 observations:
1. The memory usage of my app shoots up by about 100MB+ (130MB -> 230MB+).
2. It takes much longer to deploy the application (1.5 min -> 7 min).

Are these expected or am I missing something?

**Comment by simonz130** [comment]
Could you please share your sample app so we can try to reproduce? As far as deployment time concerned, did you try to redeploy your app without the logging library dependency to see whether the increase in deployment time is associated with the logging library usage?

**Comment by deepfriedbrain** [comment]
@simonz130 How should I send the app to you? I've created a zip file.

The deployment without the logging library takes about 2 mins. With the logging library, I've seen it even take 16-20mins.

**Comment by simonz130** [comment]
can you push it to github and share the link to the repo with your demo code to reproduce?

**Comment by deepfriedbrain** [comment]
@simonz130 You can find it here: https://github.com/deepfriedbrain/example-services

**Comment by minherz** [comment]
hi,
I apologies for neglecting this issue for such a long period of time. is it still relevant?
I would recommend to flatten the BOM to ensure that the migration to Java 11 did not trigger additional dependencies.
The `google-cloud-logging-logback` package declares dependency on the `google-cloud-logging` package. So, if you change the dependency in your pom from latter to former then you should expect an increase in the total memory footprint during runtime.
However you aren't referencing the memory footprint i.e. the memory consumed by the loaded packages but the memory usage i.e. heap memory allocations performed by the application. The use of the logback adapter instead of directly writing logs to Cloud Logging should not lead to such increase in the usage.
We cannot profile your application to discovery the main memory intensive components. We would recommend to using Cloud Profiler with memory profile enabled to try and identify relevant components.

**Comment by minherz** [comment]
I am closing this issue as not being activity for over a year. Feel free to reopen it if you have new information.
