### ISSUE TITLE
Better support for modyfing log message

### ISSUE THREAD

**Issue by Fadelis** [googleapis/java-logging-logback#350]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**

Hi! I have a use case where I'd like to mask sensitive information from appearing in the logs in one central place. With basic console logback appender it's possible to achieve this by using `encoder` property, but this is not available in GCP logger appender. So I've tried to achieve this by using `LoggingEventEnhancer` in a quick and naive approach:
```java
@Override
public void enhanceLogEntry(Builder builder, ILoggingEvent e) {
    var maskedMessage = maskMessage(e.getFormattedMessage());
    var jsonContent = Map.of("message", maskedMessage.trim());
    builder.setPayload(Payload.JsonPayload.of(jsonContent));
}
```
which would be fine, but it seems the library adds some additional fields to the payload on certain conditions:
https://github.com/googleapis/java-logging-logback/blob/99e25cbd2ccaadbe0b3b0523db86ab14616db125/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L305-L307

So in order to not overwrite these values and any possible values added with future updates I've ended up with this workaround:
```java
  @Override
  public void enhanceLogEntry(Builder builder, ILoggingEvent event) {
    var payloadData = getInitialPayloadData(builder);
    var maskedMessage = maskMessage(event.getFormattedMessage());
    payloadData.put("message", maskedMessage.trim());
    builder.setPayload(Payload.JsonPayload.of(payloadData));
  }

  private Map<String, Object> getInitialPayloadData(Builder builder) {
    var originalPayload = builder.build().getPayload();
    if (originalPayload.getType() == Type.JSON) {
      // extract original payload data as the data map might contain not only the message entry
      var originalPayloadData = ((Payload.JsonPayload) originalPayload).getDataAsMap();
      return new HashMap<>(originalPayloadData);
    }
    return new HashMap<>();
  }
```
But this feels a bit hacky and inefficient (building before retrieving the payload, casting)...

So I was wondering if it would be possible to improve the library for this use case, or maybe there's something there already that I'm not aware of?

**Describe the solution you'd like**

Maybe not having additional properties in the payload, so they wouldn't get overwritten, or explicit builder method to only set the message.

**Comment by minherz** [comment]
Hi Paulius,
Thank you for submitting your question. There are a couple of ways to resolve the problem:

- The recommended approach for obfuscating data sent to Google Cloud is using [DLP](https://cloud.google.com/dlp) service. The logs can be configured for export to BigQuery or storage bucket and obfuscated. If combined with exclusion rules the logs will not be available for Log Explorer and cannot be used to calculated log-based metrics but the information will be centrally stored and browsable.
- You can use logback enhancer that inherits from [LoggingEnhancer](https://github.com/googleapis/java-logging/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/LoggingEnhancer.java) (see [code snippet](https://github.com/googleapis/java-logging-logback/blob/master/samples/snippets/src/main/java/com/example/logging/logback/enhancers/ExampleEnhancer.java) for an example).

I would also like to understand more about your requirements for obfuscating information. I am asking this because the location of the log payload is well defined (`jsonPayload.message`) field, so applying the `maskMessage()` can be targeted to this particular value.

You also has to take into account that running your application in Google Cloud managed environments (e.g. GKE or AppEngine) will result in automatic logging of all output to STDOUT and STDERR which might not be covered by the `maskMessage()` logic. So, the use of DLP could be a preferred approach.

**Comment by minherz** [comment]
I am closing the issue for now. Please, let us know if you need further assistance about this.
