### ISSUE TITLE
Bad enhancer class name is silently ignored

### ISSUE THREAD

**Issue by sinelaw** [googleapis/java-logging-logback#747]
Passing a wrong class name (string) for the LoggingAppender enhancers causes no error: no exception is thrown (and even no error is written to the logs). This makes it easy to miss changes such as class renames breaking production logs.

Expected behavior: throw an exception if enhancer class can't be loaded

This is caused by a catch-all in https://github.com/googleapis/java-logging-logback/blob/main/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L278

**Comment by sinelaw** [comment]
Example fix https://github.com/sinelaw/java-logging-logback/commit/04f9ff585b00d1a83b8500ffa261cc3ea16070c4

**Comment by losalex** [comment]
Thanks @sinelaw for opening this issue and sorry this took to long to answer!
Unfortunately, I believe this fix cannot be done as suggested since it is a breaking change (e.g. throwing exception on wrong class name could break many library users). 
I am also not sure if a fix worth an effort - it seems this issue does not happen for too many users and also seems to be a corner case (e.g. changing class name does not happens lot), so I would tend to close this issue. 
Please let me know if you OK with closing this issue.

**Comment by cindy-peng** [comment]
Closing issue as no response from the customer and this is not a prioritized working item for the team at this moment.
