### ISSUE TITLE
Size of the dependencies - all really required ?

### ISSUE THREAD

**Issue by yan-hic** [googleapis/java-logging-logback#842]
We want to implement the GLogging appender for `java.util.logging handler` in a legacy j2ee app - read, no code change.
However, due to the additional dependencies, our `war` web container has doubled in size ! 

Looking at the below, there are 2 libraries related to `grpc` which have excessive sizes compared to the feature we want to implement, namely:
1. compress log
2. send it through `http`

None require additional dependencies.

![image](https://user-images.githubusercontent.com/25224265/190247944-16bc8e4b-f4b7-4ed9-b742-88252fafc741.png)

Can these libs be safely removed - without trial and error ?
If not, do stripped versions exist to only support the appender ?

Thanks !

**Comment by losalex** [comment]
@yan-hic , thanks a lot for reaching out!
I am really sorry to hear about your trouble, but unfortunately we do not have stripped appender version and currently there are no plans to add a such. This library depends on `google-cloud-logging` which depends on `grpc` libraries and I am not sure if we can safely remove those since it requires creating a separate package compiled from code which is not referencing any `grpc` related interfaces. There is a possibility to make an exercise to take code from [java-logging-logback](https://github.com/googleapis/java-logging-logback) and [java-logging](https://github.com/googleapis/java-logging) repositories, combine it and remove all code related to `grpc`, but I afraid it might be a bit too much effort...
Please let me know how else I can assist you.

**Comment by losalex** [comment]
@yan-hic , I am closing this issue for now - as I mentioned before we do not have plans to support stripped appender version in foreseen future. Feel free to comment or reactivate if you have any more questions or suggestions
