### ISSUE TITLE
Logging with google-cloud-logging-logback is not grouping request logs

### ISSUE THREAD

**Issue by mgenov** [googleapis/java-logging-logback#94]
#### Environment details

1. Logging
2. OS type and version: Linux
3. Java version: 11
4. google-cloud-java version(s): 0.103.0-alpha

#### Code example

```java
class TraceLoggingEnhancer : LoggingEnhancer {
  override fun enhanceLogEntry(builder: LogEntry.Builder) {
    val req = HttpContext.get() ?: return
    val projectId = ServiceOptions.getDefaultProjectId();
    val spanId = req.headers("x-b3-spanid")
    val traceId = req.headers("x-b3-traceid")

    builder.setHttpRequest(HttpRequest.newBuilder()
            .setRequestUrl(req.url())
            .setStatus(200)
            .setUserAgent(req.userAgent())
            .setRequestMethod(HttpRequest.RequestMethod.valueOf(req.requestMethod()))
            .build())

    builder.setTrace(composeFullTraceName(projectId, traceId))
    builder.setSpanId(spanId)
  }

  private fun composeFullTraceName(projectId: String, traceId: String): String {
    return "projects/$projectId/traces/$traceId";
  }

}
```

#### Any additional information below	
The log lines: line1 and line2 are not rendered as single log entry as on GAE or on Flexible Environment. 

![image](https://user-images.githubusercontent.com/209223/62824471-1d7a5600-bba7-11e9-90eb-2ebb6745b0bb.png)

**Comment by codyoss** [comment]
cc @chingor13

**Comment by simonz130** [comment]
Logback is using AsyncAppenderWorker threads (different threads than what's handling incoming requests). 
![image](https://user-images.githubusercontent.com/32641282/83691519-278e9a80-a5a7-11ea-83a2-f069324a777b.png)
So when incoming request comes in, the traceId is set in customer's TraceLogFilter code on the thread that handles that request. It uses Google's TraceLoggingEnhancer to set the TraceId. TraceLoggingEnhancer stores its data in thread local storage, so the same traceId is available in all getCurrentTraceId calls that happen on the same thread. However when log entry is sent with logback to the appenders and is being enhanced (in our case, with traceId), it's done on a different thread (AsyncAppenderWorker) than the one that is handling the incoming request. Therefore, TraceLoggingEnhancer.getCurrentTraceId will return null when called in AsyncAppenderWorker. When enhancing the log entry with labels, there is no request-specific information that is meant to be there, so the problem is not relevant. 

In order to allow enriching the log entry with traceId or any other request specific info, we need to provide a callback on the library side that's running on a user thread instead of the logback thread. This is a new feature, not a bug in existing functionality, which we plan to address soon.

**Comment by darewreck54** [comment]
@simonz130 Thanks for the clarification.  Whats the ETA for this new feature and is there something I can subscribe to so that I can follow it?  

Just out of curiosity what was the intention of the usage of TraceLoggingEnhancer.  I figured that being able to associate a traceId generated from a request would be a common use case.  Am I using it incorrectly?

**Comment by asodja** [comment]
I played with this before I saw this issue. And it seems that it works if you implement `LoggingEventEnhancer` and you pass trace id to MDC. You can access MDC from `ILoggingEvent e` in enchancer like `e.getMDCPropertyMap().get("your-trace-id-key")`. You can register LoggingEventEnhancer like:
```
<appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
    <loggingEventEnhancer>org.example.logging.MyLoggingEventEnhancer</loggingEventEnhancer>
    ...
</appender>
````
But I tried with just few requests and not with a lot of traffic.

Hope this helps.

**Comment by zmeggyesi** [comment]
While a roundabout way, what @asodja proposes _is_, in fact, the solution.

At the start of your request, you need to grab the `x-cloud-trace-context` header's value from the request, retrieve the project ID, and add the resulting trace ID to your MDC, with something like `MDC.put("logging.googleapis.com/trace", String.format("projects/%s/traces/%s", project, traceId))`.  
StackDriver will then automatically collate all loglines with the same trace ID under the initial request that spawned the entry.

**Comment by pouyanjazayeri** [comment]
I tried the solution suggested by @asodja and @zmeggyesi , there are a couple of details missing in their description but I got it to work in the following way:

logback config should contain:

```
<appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
    <resourceType>gae_app_standard</resourceType>
    <loggingEventEnhancer>com.google.cloud.logging.logback.TraceLoggingEventEnhancer</loggingEventEnhancer>
    ....
  </appender>
```

TraceLoggingEventEnhancer will make sure to set the traceid correctly from MDC.

and then using a servlet filter as followed:

```
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
 
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.slf4j.MDC; 

@Component
public class TraceFilter extends OncePerRequestFilter {
 
    @Override
    protected void doFilterInternal(HttpServletRequest httpServletRequest,
                                    HttpServletResponse httpServletResponse,
                                    FilterChain filterChain)
                                    throws ServletException, IOException {
        String traceId = httpServletRequest.getHeader("x-cloud-trace-context");
        MDC.put("logging.googleapis.trace", String.format("projects/%s/traces/%s", "YOUR_PROJECT_ID", traceId.split("/")[0]));
        filterChain.doFilter(httpServletRequest, httpServletResponse);
    }
}
```

Replace YOUR_PROJECT_ID with the correct value and your logging statements will be grouped under the request log.

**Comment by zmeggyesi** [comment]
@pouyanjazayeri Thanks for collecting the full solution - eventually, I arrived at the same conclusion and it's been running fine for a year now.

The only pain point is that it requires a `Filter` and an `MDC` to work, and not out-of-the-box like the previous versions.  
Also, once you group the logs like this, you cannot filter them! Example: I have three separate logs, one for my framework, one for the app code, and one for Objectify (which has been throwing me for loops too, hence its debug logging); once you open the `reuqest_log` in Stackdriver, you will not be able to drop/hide the Objectify logs.

**Comment by pouyanjazayeri** [comment]
adding the solution again since I deleted it by mistake:

add the following to your logback config file:

```
    <appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender">
        <resourceType>gae_app_standard</resourceType>
        <loggingEventEnhancer>com.google.cloud.logging.logback.TraceLoggingEventEnhancer</loggingEventEnhancer>
       <log>appengine.googleapis.com/request_log</log>
      .....
    </appender>
```

the use an http filter to set the trace in the MDC:

```
package com.example.appengine.springboot;


import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
 
import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import org.slf4j.MDC; 
import com.google.cloud.logging.logback.TraceLoggingEventEnhancer;

@Component
public class TraceFilter extends OncePerRequestFilter {
 
    @Override
    protected void doFilterInternal(HttpServletRequest httpServletRequest,
                                    HttpServletResponse httpServletResponse,
                                    FilterChain filterChain)
                                    throws ServletException, IOException {
        String traceId = httpServletRequest.getHeader("x-cloud-trace-context");
        String trace = String.format("projects/%s/traces/%s", "YOUR_PROJECT_ID", traceId.split("/")[0]);
        MDC.put("logging.googleapis.trace", trace);
        filterChain.doFilter(httpServletRequest, httpServletResponse);
    }
}
```
replace YOUR_PROJECT_ID with your actual project id. Note that only the first part before "/" is used from the x-cloud-trace-context header.


Now the logs should be grouped in the request log.
